### ISSUE TITLE
The ability to localise/translate the site and manual

### ISSUE THREAD

**Issue by SecularSteve** [inputlabs/website#51]
If this is going to appeal to a wider audience around the world, it's logical that it should come in multiple languages.

My suggestions are PoEdit, Weblate, or the good old fashioned manual way for users to contribute to this.

But that's just my suggestion. If there are reasons why they can't be, I won't pry on it.

**Comment by przymi** [comment]
For now we assume that people know how to use e.g. Google Translate and focus on higher priority issues. I hope that is fair.
